import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import imgFirstCard from "../public/images/phone.png";

import { Header } from "../components/Header";
import { ProductCard } from "../components/ProductCard";

import styles from "../styles/Home.module.scss";
import { Footer } from "../components/Footer";

const Home: NextPage = () => {
  const img = "";
  return (
    <>
      <Header />
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="" />
        </Head>

        <main className={styles.main}>
          <div className={styles.productsList}>
            <ProductCard
              imageURL={imgFirstCard}
              brands={["2", "1"]}
              price={"240"}
            />
          </div>
        </main>
      </div>
      <Footer />
    </>
  );
};

export default Home;
